#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.23a
#  in conjunction with Tcl version 8.6
#    Jun 11, 2019 05:12:44 PM CEST  platform: Linux

import sys

import bierprototype

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk

    py3 = False
except ImportError:
    import tkinter.ttk as ttk

    py3 = True


def set_Tk_var():
    global txt_inhalt
    txt_inhalt = tk.StringVar()
    txt_inhalt.set('30,0 l')
    global txt_gesamtverbrauch
    txt_gesamtverbrauch = tk.StringVar()
    txt_gesamtverbrauch.set('0,0 l')


def manual():
    print('bierprototype_support.manual')
    sys.stdout.flush()


def ok():
    print('bierprototype_support.ok')
    sys.stdout.flush()


def p():
    print('bierprototype_support.p')
    sys.stdout.flush()


def reset():
    print('bierprototype_support.reset')
    txt_inhalt.set('30,0 l')
    sys.stdout.flush()


def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top


def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None


if __name__ == '__main__':

    bierprototype.vp_start_gui()
