#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.23a
#  in conjunction with Tcl version 8.6
#    Jun 11, 2019 05:12:33 PM CEST  platform: Linux

import sys

from bierprototype_support import bierprototype_support
from sensormanager.sensormanager import Sensormanager

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk

    py3 = False
except ImportError:
    import tkinter.ttk as ttk

    py3 = True


def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    bierprototype_support.set_Tk_var()
    top = Bierzaehler(root)
    bierprototype_support.init(root, top)
    root.mainloop()


w = None


def create_Bierzaehler(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel(root)
    bierprototype_support.set_Tk_var()
    top = Bierzaehler(w)
    bierprototype_support.init(w, top, *args, **kwargs)
    return (w, top)


def destroy_Bierzaehler():
    global w
    w.destroy()
    w = None


class Bierzaehler:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9'  # X11 color: 'gray85'
        _ana1color = '#d9d9d9'  # X11 color: 'gray85'
        _ana2color = '#ececec'  # Closest X11 color: 'gray92'
        font12 = "-family {Bitstream Vera Sans} -size 48 -weight bold " \
                 "-slant roman -underline 0 -overstrike 0"
        font13 = "-family {Bitstream Vera Sans} -size 30 -weight bold " \
                 "-slant roman -underline 0 -overstrike 0"
        font9 = "-family {Bitstream Vera Sans} -size 20 -weight bold " \
                "-slant roman -underline 0 -overstrike 0"

        top.geometry("600x450+516+216")
        top.title("Bierzähler")
        top.configure(background="#ffffff")
        top.configure(highlightbackground="#d8d8d8")

        self.btn_R = tk.Button(top)
        self.btn_R.place(relx=0.017, rely=0.022, height=99, width=106)
        self.btn_R.configure(activebackground="#5b4fff")
        self.btn_R.configure(activeforeground="white")
        self.btn_R.configure(background="#211d5e")
        self.btn_R.configure(command=bierprototype_support.reset)
        self.btn_R.configure(font=font9)
        self.btn_R.configure(foreground="#ffffff")
        self.btn_R.configure(text='''R''')
        self.btn_R.configure(width=106)

        self.btn_P = tk.Button(top)
        self.btn_P.place(relx=0.017, rely=0.267, height=99, width=106)
        self.btn_P.configure(activebackground="#5b4fff")
        self.btn_P.configure(activeforeground="white")
        self.btn_P.configure(background="#211d5e")
        self.btn_P.configure(command=bierprototype_support.p)
        self.btn_P.configure(font=font9)
        self.btn_P.configure(foreground="#ffffff")
        self.btn_P.configure(text='''P''')

        self.btn_M = tk.Button(top)
        self.btn_M.place(relx=0.017, rely=0.511, height=99, width=106)
        self.btn_M.configure(activebackground="#5b4fff")
        self.btn_M.configure(activeforeground="white")
        self.btn_M.configure(background="#211d5e")
        self.btn_M.configure(command=bierprototype_support.manual)
        self.btn_M.configure(font=font9)
        self.btn_M.configure(foreground="#ffffff")
        self.btn_M.configure(text='''M''')

        self.btn_ok = tk.Button(top)
        self.btn_ok.place(relx=0.017, rely=0.756, height=99, width=106)
        self.btn_ok.configure(activebackground="#5b4fff")
        self.btn_ok.configure(activeforeground="white")
        self.btn_ok.configure(background="#211d5e")
        self.btn_ok.configure(command=bierprototype_support.ok)
        self.btn_ok.configure(font=font9)
        self.btn_ok.configure(foreground="#ffffff")
        self.btn_ok.configure(text='''OK''')

        self.Inhaltframe = tk.LabelFrame(top)
        self.Inhaltframe.place(relx=0.25, rely=0.022, relheight=0.567
                               , relwidth=0.717)
        self.Inhaltframe.configure(relief='groove')
        self.Inhaltframe.configure(font=font9)
        self.Inhaltframe.configure(text='''Inhalt''')
        self.Inhaltframe.configure(background="#ffffff")
        self.Inhaltframe.configure(width=430)

        self.lbl_inhalt = tk.Label(self.Inhaltframe)
        self.lbl_inhalt.place(relx=0.047, rely=0.118, height=199, width=386
                              , bordermode='ignore')
        self.lbl_inhalt.configure(background="#ffffff")
        self.lbl_inhalt.configure(font=font12)
        self.lbl_inhalt.configure(text='''30,0 l''')
        self.lbl_inhalt.configure(textvariable=bierprototype_support.txt_inhalt)
        self.lbl_inhalt.configure(width=386)

        self.Gesamtverbrauchframe = tk.LabelFrame(top)
        self.Gesamtverbrauchframe.place(relx=0.25, rely=0.644, relheight=0.322
                                        , relwidth=0.717)
        self.Gesamtverbrauchframe.configure(relief='groove')
        self.Gesamtverbrauchframe.configure(font=font9)
        self.Gesamtverbrauchframe.configure(text='''Gesamtverbrauch''')
        self.Gesamtverbrauchframe.configure(background="#ffffff")
        self.Gesamtverbrauchframe.configure(width=430)

        self.lbl_gesamtverbrauch = tk.Label(self.Gesamtverbrauchframe)
        self.lbl_gesamtverbrauch.place(relx=0.023, rely=0.345, height=79
                                       , width=406, bordermode='ignore')
        self.lbl_gesamtverbrauch.configure(anchor='w')
        self.lbl_gesamtverbrauch.configure(background="#ffffff")
        self.lbl_gesamtverbrauch.configure(font=font13)
        self.lbl_gesamtverbrauch.configure(text='''0,0 l''')
        self.lbl_gesamtverbrauch.configure(textvariable=bierprototype_support.txt_gesamtverbrauch)
        self.lbl_gesamtverbrauch.configure(width=406)


if __name__ == '__main__':
    vp_start_gui()
